/* =============================================================================
 * test/agent_pr_honesty_test.js
 * -----------------------------------------------------------------------------
 * The PR description the autonomous agent writes about its own work.
 *
 * For PRs #67, #72, #73, #75 and #76 that description said:
 *
 *     **Proving test:** `test/auto-….test.js` written by Agent 4 (QA)
 *
 * Every word of which was true, and worthless. A test file had indeed been
 * written. Not one of them had ever executed a single assertion — they imported
 * `jsdom`, which this repo does not have, or reached for `module.default` on
 * browser IIFEs that export nothing. The sentence describes an artifact and
 * reads as evidence, and that gap is what let five bad PRs look reviewable.
 *
 * #78 made the pipeline run the candidate red→green before drafting a PR. This
 * file guards the other half: that the PR body SAYS which of those two worlds
 * it is in. A verification nobody can see in the PR is a verification that
 * changes no reviewer's decision — the same "computed and never consumed"
 * defect, one level up.
 * ===========================================================================*/

import { describe, it, expect } from 'vitest';
import { prBody } from '../autonomous-fix-agent.js';

const base = {
    issue: { title: 'Something is broken' },
    number: 123,
    result: {
        role: 'bug',
        review: { verdict: 'PASS', reason: 'no findings' },
        providers: { author: 'gemini', security: 'mistral', qa: 'groq' },
    },
    testWritten: 'test/auto-wealthflow-icons-123.test.js',
};

const verified = () => prBody({ ...base, result: { ...base.result, verified: true } });
const unverified = () => prBody({ ...base, result: { ...base.result, verified: false } });
const noTest = () => prBody({ ...base, result: { ...base.result, verified: false }, testWritten: null });

describe('the PR body distinguishes a test that ran from a test that exists', () => {
    it('states the red→green result when the test was verified', () => {
        const b = verified();
        expect(b).toMatch(/FAILS against the original file and PASSES against this one/);
        expect(b).toMatch(/executed and verified/);
    });

    it('warns loudly when a test exists but was NOT verified', () => {
        const b = unverified();
        expect(b).toMatch(/NOT verified red→green/);
        expect(b).toMatch(/Do not treat it as evidence/);
    });

    it('never claims verification it did not do', () => {
        // The load-bearing assertion. If this ever passes on the unverified
        // body, the PR description is lying the way it lied five times.
        expect(unverified()).not.toMatch(/executed and verified/);
        expect(noTest()).not.toMatch(/executed and verified/);
    });

    it('the two bodies actually differ — not vacuous', () => {
        expect(verified()).not.toBe(unverified());
    });

    it('says so plainly when there is no test at all', () => {
        expect(noTest()).toMatch(/\*\*Proving test:\*\* none/);
        expect(noTest()).toMatch(/needs human review/);
    });
});

describe('the gate list reflects what actually ran', () => {
    it('claims the double execution only when it happened', () => {
        expect(verified()).toMatch(/proving test was executed twice/);
        expect(unverified()).toMatch(/NOT executed red→green/);
        expect(unverified()).not.toMatch(/executed twice/);
    });
});

describe('the body is still a well-formed PR description', () => {
    it('closes the issue it was drafted for', () => {
        expect(verified()).toMatch(/Closes #123/);
    });

    it('names the author, the reviewer and the verdict', () => {
        const b = verified();
        expect(b).toMatch(/Authored by:\*\* bug agent via `gemini`/);
        expect(b).toMatch(/Agent 5 \(Chaos Security\) via `mistral`/);
        expect(b).toMatch(/Security verdict:\*\* PASS — no findings/);
    });

    it('carries the attribution footer', () => {
        expect(verified()).toMatch(/_Generated by \[Claude Code\]/);
    });

    it('survives a missing issue title and missing providers', () => {
        // Called on a degraded path, this must not throw — a crash here would
        // lose an otherwise good fix.
        expect(() => prBody({ number: 1, result: {}, testWritten: null })).not.toThrow();
        expect(() => prBody()).not.toThrow();
    });
});
