import { readFile } from 'node:fs/promises';
import vm from 'node:vm';

const LIMIT = 16 * 1024 * 1024;
let runtime;
async function engine() {
    if (!runtime) runtime = Promise.all([
        readFile(new URL('./wealthflow-statement-parser.js', import.meta.url), 'utf8'),
        readFile(new URL('./wealthflow-layout-memory.js', import.meta.url), 'utf8'),
    ]).then(([parser, memory]) => {
        const context = vm.createContext({ window: {}, console: { log() {} } }, { codeGeneration: { strings: false, wasm: false } });
        vm.runInContext(parser, context, { timeout: 2000 });
        vm.runInContext(memory, context, { timeout: 2000 });
        return context;
    });
    return runtime;
}
export function layoutBank(bank) {
    return String(bank || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}
function source(text) {
    if (typeof text !== 'string' || !text.length || Buffer.byteLength(text) > LIMIT || text.split('\n').length > 20000) throw new Error('INVALID_LAYOUT_SOURCE');
    return text;
}
// Only the bounded date shapes generated by the repository's learner are legal.
// In particular arbitrary persisted/user regular expressions are never compiled.
function safeShape(re) {
    if (typeof re !== 'string' || re.length > 150) return false;
    const part = /^(\(\\d\{(?:1,2|2|3|4)\}\)|\(\(\?:jan\|feb\|mar\|apr\|may\|jun\|jul\|aug\|sep\|oct\|nov\|dec\)\[a-z\]\*\))/;
    let rest = re;
    for (let i = 0; i < 3; i++) {
        const match = rest.match(part);
        if (!match) return false;
        rest = rest.slice(match[0].length);
        if (i < 2) {
            const next = rest.indexOf('(');
            if (next < 0) return false;
            const sep = rest.slice(0, next);
            if (sep !== '' && sep !== '\\s{1,2}' && !/^(?:\\[.*+?^${}|\[\]\\]|[^\w\s()\\]){1,2}$/.test(sep)) return false;
            rest = rest.slice(next);
        }
    }
    return rest === '';
}
export function validateCloudTemplate(template, bank) {
    const t = template?.template || template;
    if (!t || t.v !== 1 || !['dmy', 'mdy', 'ymd'].includes(t.order) || typeof t.joinNext !== 'boolean' || !safeShape(t.re) || !layoutBank(bank) || layoutBank(t.bank) !== layoutBank(bank)) throw new Error('INVALID_LAYOUT_TEMPLATE');
    return { v: 1, re: t.re, order: t.order, joinNext: t.joinNext, bank: String(t.bank).slice(0, 200), learnedAt: Number.isFinite(t.learnedAt) ? t.learnedAt : 0, id: String(t.id || '').slice(0, 100) };
}
async function run(expression, values) {
    const context = await engine();
    Object.assign(context, values);
    try { return JSON.parse(JSON.stringify(vm.runInContext(expression, context, { timeout: 4000 }))); }
    finally { for (const key of Object.keys(values)) delete context[key]; }
}
export async function normalizeCloudLayout(text, template, bank) {
    return run('window.WFLayoutMemory.normalise(layoutText, layoutTemplate)', { layoutText: source(text), layoutTemplate: validateCloudTemplate(template, bank) });
}
export async function proposeCloudLayouts(text, { bank } = {}) {
    if (!layoutBank(bank)) throw new Error('INVALID_LAYOUT_BANK');
    return run('window.WFLayoutMemory.propose(layoutText, null, {bank:layoutBankName})', { layoutText: source(text), layoutBankName: bank });
}
function rowKey(row) {
    const date = String(row?.date || '');
    const value = Number(row?.amount);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || new Date(`${date}T00:00:00Z`).toISOString().slice(0, 10) !== date || !(value > 0) || !Number.isFinite(value) || !Number.isSafeInteger(Math.round(value * 100)) || Math.abs(value * 100 - Math.round(value * 100)) > 0.000001 || !['credit', 'debit'].includes(row?.direction)) throw new Error('INVALID_LAYOUT_ROWS');
    return `${date}|${Math.round(value * 100)}|${row.direction}`;
}
export async function learnCloudLayout(text, confirmedRows, { bank } = {}) {
    source(text);
    if (!layoutBank(bank) || !Array.isArray(confirmedRows) || !confirmedRows.length || confirmedRows.length > 5000) throw new Error('INVALID_LAYOUT_ROWS');
    const wanted = confirmedRows.map(rowKey).sort();
    const result = await run('window.WFLayoutMemory.learn(layoutText, layoutRows, null, {bank:layoutBankName})', { layoutText: text, layoutRows: confirmedRows, layoutBankName: bank });
    if (!result.ok) return result;
    const actual = result.rows.map(rowKey).sort();
    if (JSON.stringify(wanted) !== JSON.stringify(actual)) return { ok: false, reason: 'The confirmed rows do not reproduce the entire statement reading.' };
    result.template = validateCloudTemplate(result.template, bank);
    return result;
}
